// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaulcQWEhraImSFnLeDVRmjdD61hi1ruI',
    appId: '1:709166762892:web:c61e61721977676212e4a9',
    messagingSenderId: '709166762892',
    projectId: 'myflutter-7ff03',
    authDomain: 'myflutter-7ff03.firebaseapp.com',
    storageBucket: 'myflutter-7ff03.appspot.com',
    measurementId: 'G-LSWWC159VF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKx1gIgj-yqvkIqQ9xzI083zSe7fI0C_U',
    appId: '1:709166762892:android:b913e9f3134a584012e4a9',
    messagingSenderId: '709166762892',
    projectId: 'myflutter-7ff03',
    storageBucket: 'myflutter-7ff03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPlbuVTUphRp-79e4zaSW0u6ZXOuRJEZA',
    appId: '1:709166762892:ios:7feb04543c38565412e4a9',
    messagingSenderId: '709166762892',
    projectId: 'myflutter-7ff03',
    storageBucket: 'myflutter-7ff03.appspot.com',
    iosBundleId: 'com.example.kebab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPlbuVTUphRp-79e4zaSW0u6ZXOuRJEZA',
    appId: '1:709166762892:ios:545c5c1f96ea442112e4a9',
    messagingSenderId: '709166762892',
    projectId: 'myflutter-7ff03',
    storageBucket: 'myflutter-7ff03.appspot.com',
    iosBundleId: 'com.example.kebab.RunnerTests',
  );
}
